import "@mantine/core/styles.css";

import type { Metadata } from "next";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning={true}>
			<head>
				<ColorSchemeScript defaultColorScheme="auto" />
			</head>
			<body suppressHydrationWarning={true}>
				<MantineProvider>{children}</MantineProvider>
			</body>
		</html>
	);
}
